### ISSUE TITLE
Opensource checklist

### ISSUE THREAD

**Issue by annejan** [minvws/nl-rdo-php-audit-logger#9]
- [x] [Fix CI](https://github.com/minvws/nl-rdo-php-audit-logger/issues/4)
- [ ] [Update documentation](https://github.com/minvws/nl-rdo-php-audit-logger/issues/3)
- [ ] Sanity check the code and commits
- [x] Check license file(s) and correct if needed
- [ ] Code review by security team
- [ ] Readme check
  - [ ] Readability (use of domain terminology)
  - [ ] Make sure you can get a working application
- [ ] External code quality review
- [ ] Determine repository synchronisation scheme (with or without history)
- [ ] Create public repo, make sure to setup branch protection
- [ ] Get written approval 
  - [ ] Product owner
  - [ ] Management team (RDO specific: CTO)
- [ ] Update GH Actions to not use org/repo secrets
- [ ] Configure repo for public use
- [ ] Celebrate 🎉
